# Rubocop version -  0.49.1
AllCops:
  Include:
    - Gemfile
    - Rakefile
  Exclude:
    - bin/**/*
    - vendor/**/*
    - tmp/**/*
    - script/**/*

Metrics/ClassLength:
  Max: 200
  CountComments: false

Lint/RescueException:
  Enabled: false

Metrics/AbcSize:
  Max: 43

Metrics/CyclomaticComplexity:
  Max: 18

Metrics/PerceivedComplexity:
  Max: 12

Lint/AmbiguousRegexpLiteral:
  Enabled: false

CollectionMethods:
  Enabled: false

Encoding:
  Enabled: false

LineLength:
  Max: 420

Documentation:
  Enabled: false

CaseIndentation:
  Enabled: false

DotPosition:
  Enabled: false

MethodLength:
  CountComments: false
  Max: 25

AlignParameters:
  Enabled: false

IfUnlessModifier:
  Enabled: false

TrailingCommaInLiteral:
  Enabled: false

# Configuration parameters: CountComments.
Metrics/ModuleLength:
  Max: 172

EndOfLine:
  Enabled: false

Style/Semicolon:
  Enabled: false

Style/RegexpLiteral:
  AllowInnerSlashes: true

Metrics/ParameterLists:
  Max: 6
